version: '3.8'

services:
  webapp:
    image: ducminh1710/exe201:latest
    ports:
      - "5146:5146"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=AgricultureSmart;User=sa;Password=SecurePassword2025!;TrustServerCertificate=true;
    depends_on:
      - sqlserver
    networks:
      - appnet

  sqlserver:
  image: mcr.microsoft.com/mssql/server:2022-latest
  container_name: sqlserver
  ports:
    - "127.0.0.1:1433:1433"
  environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=SecurePassword2025!
  volumes:
    - sql_data:/var/opt/mssql
  networks:
    - appnet

  fe:
    image: fe:latest
    ports:
      - "3000:3000"
      
networks:
  appnet:
    driver: bridge

volumes:
  sql_data: