version: '3.8'

services:
  webapp:
    image: ducminh1710/exe201:latest
    ports:
      - "5146:5146"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=AgricultureSmart;User=sa;Password=NewPass2025!ExeSmart;TrustServerCertificate=true;
    depends_on:
      - sqlserver
    networks:
      - appnet
    restart: unless-stopped

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=NewPass2025!ExeSmart
      - MSSQL_PID=Express
      - MSSQL_AGENT_ENABLED=true
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - appnet
    restart: unless-stopped

  fe:
    image: fe:latest
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://webapp:5146
      - NODE_ENV=production
      - NEXT_PUBLIC_SITE_URL=http://14.225.212.92:3000
    networks:
      - appnet
    restart: unless-stopped
    depends_on:
      - webapp

networks:
  appnet:
    driver: bridge

volumes:
  sql_data:
