version: '3.8'

services:
  webapp:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5146:5146"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=AgricultureSmart;User=sa;Password=MyNewSecure@2025!EXE;TrustServerCertificate=true;
    depends_on:
      - sqlserver
    networks:
      - appnet
    restart: unless-stopped

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyNewSecure@2025!EXE
      - MSSQL_PID=Express
      - MSSQL_AGENT_ENABLED=true
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - appnet
    restart: unless-stopped

  fe:
    build:
      context: ./Agriculture_Smart_FE
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://160.30.113.224:5146
      - NODE_ENV=production
      - NEXT_PUBLIC_SITE_URL=http://160.30.113.224:3000
    networks:
      - appnet
    restart: unless-stopped
    depends_on:
      - webapp

networks:
  appnet:
    driver: bridge

volumes:
  sql_data:
